### ISSUE TITLE
k8s deployment strategies

### ISSUE THREAD

**Issue by HarshadRanganathan** [HarshadRanganathan/harshadranganathan.github.io#106]
[1] Ensure a min replica of 2 for all critical apps
 
Reasoning – If one replica goes down for any reason, requests will still get served by the other replica
 
 
[2] Roll-out changes one pod at a time
 
Please add below config to both API and GraphQL deployment charts
 
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
```
 
Note – This may not be a suitable configuration for some apps as depending on the number of replicas, this will increase the deployment time – however this configuration will ensure the existing volume handling is not impacted
 
 
[3]  Do not set CPU limits as it may result in aggressive throttling causing performance issues if misconfigured. However, ensure correct CPU requests are set for your app.
 
e.g. Do not set below setting
```
resources:
   limits:
      cpu: 512m
```
